blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('price/',views.price),
    path("<int:id>/",views.google),
    path('posts/', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
    
     
]

blog/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('home/',views.home, name='home'),
    path('blog/',views.blog, name='blog'),
    path("<int:id>/",views.post, name='post'),
    path('about/', views.about, name='about'),  
    path('contact/', views.contact, name='contact'),
    path('post_new/',views.post_new, name='post_new'),
]

blog/users/urls.py
from django.urls import path
from . import views 

app_name = "users"

urlpatterns = [
    path('register/',views.register, name='register'),
    path('login/',views.login_view, name='login'),
    path('logout/', views.user_logout, name='logout'),

]

blog/posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length= 75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateField(auto_now_add= True)

    def __str__(self):
        return self.title
    

blog/users/models.py
from django.db import models

# Create your models here.

blog/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect, Http404
from django.urls import reverse
from .models import Post
from django.contrib.auth.decorators import login_required

# Create your views here.
posts =[
    {
        'id': 1,
        'title': 'Chunghua Aluminium',
        'content': 'Chunghua Aluminium is located in Dhaka, Bangladesh. They specialize in the production of high-quality aluminium profiles, used for doors, windows, and various industrial applications. The company is known for its durable and reliable products in the construction sector.'
    },
    {
        'id': 2,
        'title': 'Dhaka Thai Aluminium',
        'content': 'Dhaka Thai Aluminium is one of the leading aluminium companies in Bangladesh, based in Gazipur. They manufacture a wide range of aluminium products including profiles for doors, windows, and curtain walls. The company is a key supplier to both domestic and international markets.'
    },
    {
        'id': 3,
        'title': 'Alco Aluminium',
        'content': 'Alco Aluminium is situated in Chittagong, Bangladesh. Their product line includes aluminium sheets, extrusions, and coils, which are used in the construction, automotive, and packaging industries. Alco is known for its innovative solutions and sustainable practices.'
    },
]

def home(request):

    return render(request,'posts/home.html',{'username': 'Reader'})


def blog(request):
    html=""
    for post in posts:
        html += f'''
            <div>
            
            <a href="/post/{post['id']}"> 
                <h1>{post['id']} - {post['title']}</h1></a>
                <p> {post['content']}</p>
            
            </div>
        
        '''
    return render(request,'posts/blog.html',{'posts': posts}) 


def post(request,id):
    print(type(id))
    return HttpResponse(f"{id}")

def post(request,id):
    valid_id = False
    for post in posts:
        if post['id'] ==id:
            post_dict = post
            valid_id = True
            break
    if valid_id:   

        return render(request, "posts/post.html", {'post_dict': post_dict})
    else:
        #return  HttpResponseNotFound("<h1>Post not Available :)</h1>")
        raise Http404()
    
    
    
            
#HttpResponseRedirect class to access another url for price
def price(request):
    return HttpResponseRedirect('https://www.banglastall.com/filter/Construction/Thai-Aluminium/ALCO')

def google(request,id):
    #Using reverse function to dynamically generate the urls
    url = reverse("post",args=[id])
    return HttpResponseRedirect(url)
    
    
def about(request):
    return render(request, 'posts/about.html')

def contact(request):
    return render(request, 'posts/contact.html')  

#redirects users to login url if they are not logged in
@login_required(login_url='users:login')
def post_new(request):
    return render(request, 'posts/post_new.html')

blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login,logout


# def register(request):
#     if request.method== "POST":
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save() 
#             auth_login(request, user)
#             return redirect("posts:blog") 
#     else:
#         form = UserCreationForm()  

#     return render(request, "users/register.html", {"form": form})

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            print("User registered successfully!")  # For debugging
            return redirect("posts:blog")
        else:
            print(form.errors)  # Log errors to the terminal for debugging
    else:
        form = UserCreationForm()

    return render(request, "users/register.html", {"form": form})



def login_view(request):
    
    if request.method == "POST":
        form = AuthenticationForm(data= request.POST)
        if form.is_valid():
            user = form.get_user() 
            auth_login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:blog")
     
    else:
        form = AuthenticationForm()  

    return render(request, "users/login.html", {"form": form})


def user_logout(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:blog")
        

blog/posts/templates/posts/about.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'posts/about.css' %}">
{% endblock css %}

{%block js%}<script src="{% static 'js/about.js'%}"defer></script> {%endblock js%}
{% block pagetitle %}About Us{% endblock pagetitle %}

{% block body %}
    <h1>About Us</h1>
    <p>
        Welcome to our blog! We are dedicated to providing information about aluminum companies in Bangladesh. 
        Our aim is to showcase the best in the industry, share insights, and connect with those who are 
        interested in aluminum products.
    </p>
    <p>
        Whether you're looking for suppliers, industry news, or simply want to learn more about aluminum, 
        you've come to the right place!
    </p>
{% endblock body %}

blog/posts/templates/posts/blog.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'posts/home.css' %}">
{% endblock css %}
{%block js%}<script src="{% static 'js/home.js'%}"defer></script> {%endblock js%}

{% block pagetitle %}
    Home Page
{% endblock pagetitle %}

{% block body %}

    
    {% if posts %}
        {% for post in posts %} 
            <div>
                <a href="{% url 'posts:post' post.id %}">
                    <h2>{{ forloop.counter }} - {{ post.title }}</h2>
                </a>
                <p>{{ post.content|truncatewords:5 }}</p>
            </div>
        {% endfor %}
    {% else %}
        <h1>No posts available</h1>
    {% endif %}
{% endblock body %}

blog/posts/templates/posts/contact.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'posts/contact.css' %}">
{% endblock css %}
{%block js%}<script src="{% static 'js/contact.js'%}"defer></script> {%endblock js%}

{% block pagetitle %}Contact Us{% endblock pagetitle %}

{% block body %}
    <h1>Contact Us</h1>
    <p>
        If you have any questions, comments, or suggestions, feel free to reach out to us. 
        You can contact us via the following methods:
    </p>
    <div class="contact-info">
        <div class="contact-item" id="phone">+880 17* *** ****</div>
        <div class="contact-item" id="email">nipa20farzana@gmail.com</div>
    </div>
    <p>
        We look forward to hearing from you!
    </p>
{% endblock body %}

blog/posts/templates/posts/home.html
    {% extends "base.html" %}
    {% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'posts/home.css' %}">
{% endblock css %} 
  
    {%block js%}<script src="{% static 'js/home.js'%}"defer></script> {%endblock js%}

    {% block pagetitle %}
        Home Page
    {% endblock pagetitle %}
    
    {% block body %}
        <h1> Hello {{ username|capfirst }} Welcome to AluBlog</h1>
        

        <p>Your one-stop platform for aluminium industry insights in Bangladesh.</p>
        
    {% endblock body %}
    

blog/posts/templates/posts/post.html
{% extends "base.html" %}

{%load static%}

{%block css%}
        <link rel= "stylesheet" href="{% static 'posts/post.css'%}">       
{%endblock css%}

{%block js%}<script src="{% static 'js/post.js'%}"defer></script> {%endblock js%}

{%block pagetitle%}post.html {%endblock pagetitle%}



{% block body %}
<h1>{{post_dict.title}} </h1>
<p>{{post_dict.content}} </p>

{% endblock body %}

blog/posts/templates/posts/post_new.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'posts/home.css' %}">
{% endblock css %}
{%block js%}<script src="{% static 'js/home.js'%}"defer></script> {%endblock js%}

{% block pagetitle %}
      New Post
{% endblock pagetitle %}

{% block body %}
 <h1>New Post </h1>

   
{% endblock body %}

blog/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%block pagetitle%}
        {%endblock pagetitle%}
    </title>


<link rel= "stylesheet" href="{% static 'style.css'%}">
<script src="{% static 'home.js'%}"defer></script>

{%block css%}  {%endblock css%}
{%block js%} {%endblock js%}

</head>
<body>
    <nav> 


        
            <a href="{% url 'posts:home' %}">Home</a>
            <a href="{% url 'posts:about' %}">About</a>
            <a href="{% url 'posts:blog' %}">Blog</a>
            <a href="{% url 'posts:contact' %}">Contact Us</a>

        {%if user.is_authenticated%}

            <a href="{% url 'posts:post_new' %}">New</a>

            <form class="logout" action="{% url 'users:logout' %}" method="post">
             {% csrf_token %}
             <button class="logout-button">Logout</button>
            </form>
        {%else%}
        
        <a href="{% url 'users:register' %}">Register</a>
        <a href="{% url 'users:login' %}">Login</a>
        {%endif%}
   </nav>
   
    {% block body %}
    {% endblock body %}


<footer>
        <p>&copy; 2024 Aluminium Blog. All rights reserved.</p>
</footer>

</body>
</html>

blog/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/register.css' %}">
{% endblock css %}
{%block js%}<script src="{% static 'js/home.js'%}"defer></script> {%endblock js%}

{% block pagetitle %}
    User Login
{% endblock pagetitle %}

{% block body %}
     <p>Login Form</p>
    <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <div class="form-fields">
                {{ form.as_p }}
                {%if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next}}" />
                {%endif%}
            </div>
    <button class="form-submit">Submit</button>



{% endblock body %}

blog/users/templates/users/register.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/register.css' %}">
{% endblock css %}
{%block js%}<script src="{% static 'js/home.js'%}"defer></script> {%endblock js%}

{% block pagetitle %}
    Register a New User
{% endblock pagetitle %}

{% block body %}
     <h1> Register a New User</h1>


        <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            <div class="form-fields">
                {{ form.as_p }}
            </div>
    
            {% if form.errors %}
                <div class="error-message">
                    <ul>
                        {% for field, errors in form.errors.items %}
                            <li><strong>{{ field }}:</strong> {{ errors|join:", " }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
    
            <button class="form-submit" type="submit">Submit</button>


    </form>
    


{% endblock body %}